baseURL = 'http://chingiztibei.com'
relativeURLs = true
languageCode = 'ru-RU'
title = 'Тибэй'
logotype = "/images/logo.svg"
theme = 'maverick'
enableRobotsTXT = true
googleAnalytics = 'UA-83734662-1'

staticDir = ['static']

defaultContentLanguage = "ru"
defaultContentLanguageInSubdir = true

[languages]
  [languages.ru]
    languageName = "Русский"
    weight = 1
    dateFormat = "02 янв, 2006"
    timeFormat = "15:04"
    [languages.ru.params]
      someParam = "Значение параметра на русском"


[permalinks]
  pages = "/:slug"

[params]
  logo = '/images/favicon.ico'
  description = "Саможит, коферайтер и синефил. Живу, пишу, фотографирую и делаю свой любимый кофе в Алматы."
  author = 'Чингиз Тибэй'
  customtextFontFamily = ""
  customheadingFontFamily = "Betmo"

[menu]
  [[menu.main]]
    identifier = "travel"
    name = "travel"
    url = "/tags/travel"
    weight = -140
  [[menu.main]]
    identifier = "blog"
    name = "blog"
    url = "/posts"
    weight = -130

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokailight'
    tabWidth = 4

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

ignoreErrors = ["error-remote-getjson"]