baseURL = 'http://chingiztibei.com'
relativeURLs = true
languageCode = 'ru-RU'
defaultContentLanguage = "ru"
defaultContentLang = "ru"
title = 'Чингиз Тибэй'
theme = 'maverick'
paginate = 5
enableRobotsTXT = true
googleAnalytics = 'UA-83734662-1'

[permalinks]
  pages = "/:slug"

[params]
  logo = '/assets/favicon.ico'
  description = "Саможит, коферайтер и синефил. Живу, пишу, фотографирую и делаю свой любимый кофе в Алматы."
  author = 'Чингиз Тибэй'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "Обо мне"
    url = "/about/"
    weight = "-110"
  [[menu.main]]
    identifier = "posts"
    name = "Блог"
    url = "/posts/"
    weight = -200

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokailight'
    tabWidth = 4

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

ignoreErrors = ["error-remote-getjson"]